/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_kryptonite_audio_fvad_FVad */

#ifndef _Included_ru_kryptonite_audio_fvad_FVad
#define _Included_ru_kryptonite_audio_fvad_FVad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      ru_kryptonite_audio_fvad_FVad
 * Method:     init
 * Signature:  (II)J
 */
JNIEXPORT jlong JNICALL Java_ru_kryptonite_audio_fvad_FVad_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:      ru_kryptonite_audio_fvad_FVad
 * Method:     process
 * Signature:  (J[S)I
 */
JNIEXPORT jint JNICALL Java_ru_kryptonite_audio_fvad_FVad_process
  (JNIEnv *, jobject, jlong, jshortArray);

/*
 * Class:      ru_kryptonite_audio_fvad_FVad
 * Method:     _1reset
 * Signature:  (JII)V
 */
JNIEXPORT void JNICALL Java_ru_kryptonite_audio_fvad_FVad__1reset
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:      ru_kryptonite_audio_fvad_FVad
 * Method:     _1close
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_ru_kryptonite_audio_fvad_FVad__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
